#server:
#    port: 8080
#    servlet:
#        context-path: /delivery
#
---
spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
            - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback-spring.xml'
                - '*.properties'
    cloud:
        vault:
            host: 127.0.0.1
            port: 8200
            scheme: http
            authentication: APPROLE
            app-role:
                role-id: ${VAULT_ROLE_ID}
                secret-id: ${VAULT_SECRET_ID}
                app-role-path: approle
            kv:
                enabled: true
                backend: secret

grails:
    profile: web
    codegen:
        defaultPackage: delivery.system.grails
    gorm:
        reactor:
            events: false

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

environments:
    development:
        encryption:
            devKey: b15217c752d2fa421084c1694ca7113f69b63602ae2b8a244319d76e96bb79c4
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    username: postgres
    password: 'postgres'
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5433/deliverydb
    test:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5433/deliverydb
    production:
        dataSource:
            dbCreate: none
            url: jdbc:postgresql://localhost:5432/deliverydb